projects:
  app:
    schemaPath: app/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: app/database/api.graphql
    extensions:
      prisma: app/database/config.yml
