language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
    - stage
before_script:
  - openssl aes-256-cbc -a -d -in key.pem.enc -out key.pem -k $ENC_KEY
script:
    - bash ./ci/test.sh
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "stage" ]; then bash ./ci/stage.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./ci/deploy.sh; fi
